### ISSUE TITLE
MiniCPM-V-2_6 Model Crashes on Image Input in LM Studio Server but Works with Text and app inside

### ISSUE THREAD

**Issue by Wannabeasmartguy** [lmstudio-ai/lmstudio-bug-tracker#116]
Hi there, I'm facing a weird problem:

When I use
MiniCPM-V-2_6 from your huggingface repo (no matter which edition, both q4 and q8 would happen), if I send a picture in lmstudio, the app works correctly; But as soon as I start the server and send it an image, I get the following error:

```plain-text
2024-09-08 23:47:41  [INFO] [LM STUDIO SERVER] Success! HTTP server listening on port 1234
2024-09-08 23:47:41  [INFO]
2024-09-08 23:47:41  [INFO] [LM STUDIO SERVER] Supported endpoints:
2024-09-08 23:47:41  [INFO] [LM STUDIO SERVER] ->	GET  http://localhost:1234/v1/models
2024-09-08 23:47:41  [INFO] [LM STUDIO SERVER] ->	POST http://localhost:1234/v1/chat/completions
2024-09-08 23:47:41  [INFO] [LM STUDIO SERVER] ->	POST http://localhost:1234/v1/completions
2024-09-08 23:47:41  [INFO] [LM STUDIO SERVER] ->	POST http://localhost:1234/v1/embeddings
2024-09-08 23:47:41  [INFO]
2024-09-08 23:47:41  [INFO] [LM STUDIO SERVER] Logs are saved into C:\Users\someone\.cache\lm-studio\server-logs
2024-09-08 23:47:41  [INFO] Server started.
2024-09-08 23:48:11  [INFO]
Received POST request to /v1/chat/completions with body: {
  "messages": [
    {
      "role": "system",
      "content": "You are a helpful assistant."
    },
    {
      "role": "user",
      "content": [
        {
          "type": "text",
          "text": "What is the content of this image?"
        },
        {
          "type": "image_url",
          "image_url": {
            "url": "data:image/jpeg;base64,iVBORw0KGgoAAAANSUhEUgAACwoAAAHJCAYAAACfGC9XAAAABHNCSVQICAgIfAhkiAAAIABJREFUe... (truncated in these logs)"
          }
        }
      ]
    }
  ],
  "model": "lmstudio",
  "max_tokens": 4096,
  "stream": false,
  "temperature": 0.5,
  "top_p": 0.5
}
2024-09-08 23:48:11  [INFO] [LM STUDIO SERVER] Running chat completion on conversation with 2 messages.
2024-09-08 23:48:13 [ERROR] The model has crashed without additional information. (Exit code: 0). Error Data: n/a, Additional Data: n/a
2024-09-08 23:48:13  [INFO] [LM STUDIO SERVER] Client disconnected. Stopping generation..
```

Besides, if I send text format propmt without images, it works fine in both lmstudio and the server.

I didn't find useful relevant information, so came here for help. Does anyone have any solution?

**Comment by yagil** [comment]
Hello @Wannabeasmartguy which version of LM Studio is this? If it’s not 0.3.2, can you please see if it still happens with it? Available from https://lmstudio.ai

**Comment by Wannabeasmartguy** [comment]
This issue happened on version 0.3.2, but it doesn't appear anymore and works just fine.
I will continue to observe for a few days and would let you know immediately if there are any other anomalies, thank you very much @yagil !

**Comment by Wannabeasmartguy** [comment]
This issue is no longer happening and will be closed

**Comment by tomorrowart** [comment]
This error occurs all the time when the model needs to work all the time
{'error': '<LM Studio error> The model has crashed without additional information. (Exit code: 0). Error Data: n/a, Additional Data: n/a'}


[2024-11-10 11:16:24.072] [error] [LMSInternal][Client=LM Studio][Endpoint=serverSessionOperationTimeConfig] Error in writable signal handler: TypeError: Cannot read properties of undefined (reading 'operationTimeConfigSignal')
    at t.ServerSessionProvider.getServerSessionOperationTimeConfigWritableSignal (C:\Users\Администратор\AppData\Local\LM-Studio\app-0.3.5\resources\app\.webpack\main\index.js:65:27562)
    at Object.handler (C:\Users\Администратор\AppData\Local\LM-Studio\app-0.3.5\resources\app\.webpack\main\index.js:81:27918)
    at t.ServerPort.receivedWritableSignalSubscribe (C:\Users\Администратор\AppData\Local\LM-Studio\app-0.3.5\resources\app\.webpack\main\index.js:238:110)
    at a.receivedMessage (C:\Users\Администратор\AppData\Local\LM-Studio\app-0.3.5\resources\app\.webpack\main\index.js:195:8009)
    at MessagePortMain.<anonymous> (C:\Users\Администратор\AppData\Local\LM-Studio\app-0.3.5\resources\app\.webpack\main\index.js:195:6782)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/browser_init:2:99562)
[2024-11-10 11:16:30.737] [error] (node:16300) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 child-exit listeners added to [f]. Use emitter.setMaxListeners() to increase limit
[2024-11-10 11:16:30.738] [error] (node:16300) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added to [f]. Use emitter.setMaxListeners() to increase limit
[2024-11-10 11:17:40.736] [error] [LMSInternal][Client=LM Studio][Endpoint=countTokens] Error in RPC handler: TypeError: Cannot read properties of undefined (reading 'indexedModelRepresentation')
    at t.ModelLoadingProvider.getInstanceBySpecifierOrThrow (C:\Users\Администратор\AppData\Local\LM-Studio\app-0.3.5\resources\app\.webpack\main\index.js:39:6892)
    at t.ModelLoadingProvider.getLLMModelBySpecifierOrThrow (C:\Users\Администратор\AppData\Local\LM-Studio\app-0.3.5\resources\app\.webpack\main\index.js:39:8641)
    at Object.handler (C:\Users\Администратор\AppData\Local\LM-Studio\app-0.3.5\resources\app\.webpack\main\index.js:65:82443)
    at t.ServerPort.receivedRpcCall (C:\Users\Администратор\AppData\Local\LM-Studio\app-0.3.5\resources\app\.webpack\main\index.js:222:76)
    at a.receivedMessage (C:\Users\Администратор\AppData\Local\LM-Studio\app-0.3.5\resources\app\.webpack\main\index.js:195:7825)
    at MessagePortMain.<anonymous> (C:\Users\Администратор\AppData\Local\LM-Studio\app-0.3.5\resources\app\.webpack\main\index.js:195:6782)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/browser_init:2:99562)
[2024-11-10 11:17:40.738] [error] [LMSInternal][Client=LM Studio][Endpoint=serverSessionOperationTimeConfig] Error in writable signal handler: TypeError: Cannot read properties of undefined (reading 'operationTimeConfigSignal')
    at t.ServerSessionProvider.getServerSessionOperationTimeConfigWritableSignal (C:\Users\Администратор\AppData\Local\LM-Studio\app-0.3.5\resources\app\.webpack\main\index.js:65:27562)
    at Object.handler (C:\Users\Администратор\AppData\Local\LM-Studio\app-0.3.5\resources\app\.webpack\main\index.js:81:27918)
    at t.ServerPort.receivedWritableSignalSubscribe (C:\Users\Администратор\AppData\Local\LM-Studio\app-0.3.5\resources\app\.webpack\main\index.js:238:110)
    at a.receivedMessage (C:\Users\Администратор\AppData\Local\LM-Studio\app-0.3.5\resources\app\.webpack\main\index.js:195:8009)
    at MessagePortMain.<anonymous> (C:\Users\Администратор\AppData\Local\LM-Studio\app-0.3.5\resources\app\.webpack\main\index.js:195:6782)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/browser_init:2:99562)
[2024-11-10 11:31:13.898] [error] [LMSInternal][Client=LM Studio][Endpoint=countTokens] Error in RPC handler: TypeError: Cannot read properties of undefined (reading 'indexedModelRepresentation')
    at t.ModelLoadingProvider.getInstanceBySpecifierOrThrow (C:\Users\Администратор\AppData\Local\LM-Studio\app-0.3.5\resources\app\.webpack\main\index.js:39:6892)
    at t.ModelLoadingProvider.getLLMModelBySpecifierOrThrow (C:\Users\Администратор\AppData\Local\LM-Studio\app-0.3.5\resources\app\.webpack\main\index.js:39:8641)
    at Object.handler (C:\Users\Администратор\AppData\Local\LM-Studio\app-0.3.5\resources\app\.webpack\main\index.js:65:82443)
    at t.ServerPort.receivedRpcCall (C:\Users\Администратор\AppData\Local\LM-Studio\app-0.3.5\resources\app\.webpack\main\index.js:222:76)
    at a.receivedMessage (C:\Users\Администратор\AppData\Local\LM-Studio\app-0.3.5\resources\app\.webpack\main\index.js:195:7825)
    at MessagePortMain.<anonymous> (C:\Users\Администратор\AppData\Local\LM-Studio\app-0.3.5\resources\app\.webpack\main\index.js:195:6782)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/browser_init:2:99562)
[2024-11-10 11:31:13.900] [error] [LMSInternal][Client=LM Studio][Endpoint=serverSessionOperationTimeConfig] Error in writable signal handler: TypeError: Cannot read properties of undefined (reading 'operationTimeConfigSignal')
    at t.ServerSessionProvider.getServerSessionOperationTimeConfigWritableSignal (C:\Users\Администратор\AppData\Local\LM-Studio\app-0.3.5\resources\app\.webpack\main\index.js:65:27562)
    at Object.handler (C:\Users\Администратор\AppData\Local\LM-Studio\app-0.3.5\resources\app\.webpack\main\index.js:81:27918)
    at t.ServerPort.receivedWritableSignalSubscribe (C:\Users\Администратор\AppData\Local\LM-Studio\app-0.3.5\resources\app\.webpack\main\index.js:238:110)
    at a.receivedMessage (C:\Users\Администратор\AppData\Local\LM-Studio\app-0.3.5\resources\app\.webpack\main\index.js:195:8009)
    at MessagePortMain.<anonymous> (C:\Users\Администратор\AppData\Local\LM-Studio\app-0.3.5\resources\app\.webpack\main\index.js:195:6782)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/browser_init:2:99562)
