### ISSUE TITLE
【Error】No Network Traffic After Install

### ISSUE THREAD

**Issue by QNLanYang** [lmstudio-ai/lmstudio-bug-tracker#158]
After installation, click `get first LLM`, the next page is always empty. Click `skip onboard` to enter home page, seems fine, but anything that requires network will not load.
I use tools to monitor network traffic, no LM Studio related traffic found.

Concerned that my English is not good, here's the Chinese feedback:
安装好软件后，初始页无法加载。跳过这一步进入软件主页面也是一样的情况，需要网络的就不能加载（比如下载新模型）。用其他工具查看发现没有任何有关LMStudio的网络流量。

App ver. 0.3.4
screenshots:
![Clip_2024-10-15_14-48-00](https://github.com/user-attachments/assets/70f2894b-405d-4ffa-9a2f-8e9ee8ec2b36)

**Comment by QNLanYang** [comment]
After some discussing in Discord, I believe that LMStudio is NOT using my system proxy. Due to all known GFW, I have no direct access to Huggingface.io, so lack of proxy might be the reason.
And I also have a part of APPlog here, hope that's useful.

```
[2024-10-17 13:59:45.192] [info]  App starting...
[2024-10-17 13:59:47.410] [info]  Hardware survey for general system resources through 'vulkan' took 394.07ms
[2024-10-17 13:59:47.647] [info]  [AppUpdater] Checking for updates... (current state: idle)
[2024-10-17 13:59:47.647] [info]  AppUpdater state changed to checking-for-updates-periodic
[2024-10-17 13:59:47.648] [info]  [AppUpdater] Fetching version info from https://versions-prod.lmstudio.ai/win32/x86/0.3.4
[2024-10-17 13:59:48.672] [info]  Checking if LM Studio dev tools exist on the system...
[2024-10-17 13:59:48.759] [info]  LM Studio dev tools are not present, copying them over to .cache/lm-studio/bin...
[2024-10-17 13:59:48.898] [info]  [AppUpdater] Received version info response
[2024-10-17 13:59:48.899] [info]  [AppUpdater] Current version: 0.3.4 (build: 5), new version: 0.3.4 (build: undefined)
[2024-10-17 13:59:48.900] [info]  No update available: 0.3.4 (build: undefined) <= 0.3.4 (build: 5)
[2024-10-17 13:59:48.900] [info]  AppUpdater state changed to idle
[2024-10-17 13:59:51.822] [error] [LMSInternal][Client=LM Studio][Endpoint=fetchModelDownloadOptions] Error in RPC handler: TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:14152:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fe (%appdata%\Local\LM-Studio\app-0.3.4\resources\app\.webpack\main\index.js:2:39478)
    at async t.HuggingFaceHub.search (%appdata%\Local\LM-Studio\app-0.3.4\resources\app\.webpack\main\index.js:91:17417)
    at async t.SearchProvider.fetchModelDownloadOptions (%appdata%\Local\LM-Studio\app-0.3.4\resources\app\.webpack\main\index.js:91:27407)
    at async Object.handler (%appdata%\Local\LM-Studio\app-0.3.4\resources\app\.webpack\main\index.js:73:25560)
[2024-10-17 13:59:51.823] [error] [LMSInternal][Client=LM Studio][Endpoint=quickSearchOne] Error in RPC handler: TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:14152:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fe (%appdata%\Local\LM-Studio\app-0.3.4\resources\app\.webpack\main\index.js:2:39478)
    at async t.HuggingFaceHub.search (%appdata%\Local\LM-Studio\app-0.3.4\resources\app\.webpack\main\index.js:91:17417)
    at async t.SearchProvider.quickSearchOne (%appdata%\Local\LM-Studio\app-0.3.4\resources\app\.webpack\main\index.js:91:24552)
    at async Object.handler (%appdata%\Local\LM-Studio\app-0.3.4\resources\app\.webpack\main\index.js:73:26976)
[2024-10-17 13:59:52.813] [error] [LMSInternal][Client=LM Studio][Endpoint=fetchModelDownloadOptions] Error in RPC handler: TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:14152:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fe (%appdata%\Local\LM-Studio\app-0.3.4\resources\app\.webpack\main\index.js:2:39478)
    at async t.HuggingFaceHub.search (%appdata%\Local\LM-Studio\app-0.3.4\resources\app\.webpack\main\index.js:91:17417)
    at async t.SearchProvider.fetchModelDownloadOptions (%appdata%\Local\LM-Studio\app-0.3.4\resources\app\.webpack\main\index.js:91:27407)
    at async Object.handler (%appdata%\Local\LM-Studio\app-0.3.4\resources\app\.webpack\main\index.js:73:25560)
[2024-10-17 13:59:52.819] [error] [LMSInternal][Client=LM Studio][Endpoint=quickSearchOne] Error in RPC handler: TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:14152:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fe (%appdata%\Local\LM-Studio\app-0.3.4\resources\app\.webpack\main\index.js:2:39478)
    at async t.HuggingFaceHub.search (%appdata%\Local\LM-Studio\app-0.3.4\resources\app\.webpack\main\index.js:91:17417)
    at async t.SearchProvider.quickSearchOne (%appdata%\Local\LM-Studio\app-0.3.4\resources\app\.webpack\main\index.js:91:24552)
    at async Object.handler (%appdata%\Local\LM-Studio\app-0.3.4\resources\app\.webpack\main\index.js:73:26976)
```
FYI, with proxy enabled, I can access Huggingface.io and other services using Web browsers, and I have already downloaded a model from Huggingface, sideload to LMS and running.

**Comment by yagil** [comment]
@QNLanYang we have a beta version that may fix this. Are you able to try it out? Available here https://lmstudio.ai/beta-releases

**Comment by QNLanYang** [comment]
> @QNLanYang we have a beta version that may fix this. Are you able to try it out? Available here https://lmstudio.ai/beta-releases

I'm glad to try the new release. Already installed it, seems this problem still exists. No traffic through proxy. Maybe I should try Clash instead of V2ray.
Thanks anyway.

**Comment by Ps7ch3** [comment]
Same issue here.

**Comment by realduzhiguo** [comment]
same issue here. Even if I use clash tun mode it still shows "no result found".

**Comment by hongjic** [comment]
same issue here, and seems it didn't fix the problem.

**Comment by shelltea** [comment]
The same issue, may I ask when system proxy will be supported?

**Comment by nieyuanhong** [comment]
same issue here

**Comment by s-nt-s** [comment]
same issue here

**Comment by tanbw** [comment]
> > [@QNLanYang](https://github.com/QNLanYang) we have a beta version that may fix this. Are you able to try it out? Available here https://lmstudio.ai/beta-releases
> 
> I'm glad to try the new release. Already installed it, seems this problem still exists. No traffic through proxy. Maybe I should try Clash instead of V2ray. Thanks anyway.

I am using clash.Same problem.

**Comment by tanbw** [comment]
I tried proxychain to force LMStudio to use the proxy.According to the logs,traffic does go through the proxy.But I got the same problem.Here are the LM error logs:

![Image](https://github.com/user-attachments/assets/fdec91b5-8517-46c8-8769-9b93e5658e89)

**Comment by yagil** [comment]
We shipped a proxying feature in beta which might solve this issue, info here: https://github.com/lmstudio-ai/lmstudio-bug-tracker/issues/256#issuecomment-2620673643

**Comment by QNLanYang** [comment]
Since the new version has built-in proxy, this issue is considered fixed.
