### ISSUE TITLE
There was an error fetching results from Hugging Face, please try again in a little bit

### ISSUE THREAD

**Issue by hzd2020** [lmstudio-ai/lmstudio-bug-tracker#256]
Use latest version, can't search and download modules  from hugging face, hit me as follow:
There was an error fetching results from Hugging Face, please try again in a little bit

How to set  lm studio to use http proxy or to set use mirror site?  hope in the next version solved

**Comment by liuzelei** [comment]
i have the same issue

**Comment by CHENCHEN-QB** [comment]
same here

**Comment by hongjic** [comment]
same here

**Comment by bobleer** [comment]
the same

**Comment by vkinger** [comment]
same problemm

**Comment by vkinger** [comment]
i meet the same problem

**Comment by guangxuanliu-leica** [comment]
same here

**Comment by yagil** [comment]
Thanks all- for new people commenting please include a screenshot of the full app when you get the issue

**Comment by YeohsCode** [comment]
Same here.
Here's my screenshot:
![image](https://github.com/user-attachments/assets/66ae98f4-75c3-469f-8a3f-e610b8c47cb2)

**Comment by YeohsCode** [comment]
> Thanks all- for new people commenting please include a screenshot of the full app when you get the issue

same issue. Here's my screenshot:
![image](https://github.com/user-attachments/assets/257c29fd-2f3b-4db3-a96e-10ae7daa2206)

**Comment by nasirannn** [comment]
same issue
system os: macOS 15.2
lm studio version: 0.3.6

<img width="1470" alt="Image" src="https://github.com/user-attachments/assets/b0566154-51db-4420-92a9-63de6af5b5e9" />

**Comment by s-nt-s** [comment]
I have the same issue

**Comment by aaaronmiller** [comment]
Experienced this same issue while utilizing a http proxy (connected to the internet via tetherfi on my phone to bypass usage restrictions on normal hotspot connections). Mac Os 15.0 , LM-Studio 0.3.8 

Was able to solve issue by utilizing "proxifier" application which succesfully routed the HTTP and HTTPS traffic through the proxy.

**Comment by yagil** [comment]
We added a new HF proxying feature in 0.3.9 Build 2 (available in beta [here](https://lmstudio.ai/beta-releases)) that might solve this problem.

Try this:

1. Download + install 0.3.9 b2 from here: https://lmstudio.ai/beta-releases, or switch to the beta channel and update in-app
2. Go to Settings (the ⚙️ bottom right) and enable this:

![Image](https://github.com/user-attachments/assets/42c18715-be1e-4710-9c1e-06e521b59be5)

If you try it, please let me know if it worked or not

**Comment by wangchao0502** [comment]
> We added a new HF proxying feature in 0.3.9 Build 2 (available in beta [here](https://lmstudio.ai/beta-releases)) that might solve this problem.
> 
> Try this:
> 
> 1. Download + install 0.3.9 b2 from here: https://lmstudio.ai/beta-releases, or switch to the beta channel and update in-app
> 2. Go to Settings (the ⚙️ bottom right) and enable this:
> 
> ![Image](https://github.com/user-attachments/assets/42c18715-be1e-4710-9c1e-06e521b59be5)
> 
> If you try it, please let me know if it worked or not

it works for me, thanks!

**Comment by Louiva2** [comment]
> We added a new HF proxying feature in 0.3.9 Build 2 (available in beta [here](https://lmstudio.ai/beta-releases)) that might solve this problem.
> 
> Try this:
> 
> 1. Download + install 0.3.9 b2 from here: https://lmstudio.ai/beta-releases, or switch to the beta channel and update in-app
> 2. Go to Settings (the ⚙️ bottom right) and enable this:
> 
> ![Image](https://github.com/user-attachments/assets/42c18715-be1e-4710-9c1e-06e521b59be5)
> 
> If you try it, please let me know if it worked or not

Also worked for me, thanks!

**Comment by workhardddd** [comment]
> We added a new HF proxying feature in 0.3.9 Build 2 (available in beta [here](https://lmstudio.ai/beta-releases)) that might solve this problem.
> 
> Try this:
> 
> 1. Download + install 0.3.9 b2 from here: https://lmstudio.ai/beta-releases, or switch to the beta channel and update in-app
> 2. Go to Settings (the ⚙️ bottom right) and enable this:
> 
> ![Image](https://github.com/user-attachments/assets/42c18715-be1e-4710-9c1e-06e521b59be5)
> 
> If you try it, please let me know if it worked or not

same issue
system os: windows 11
lm studio version: 0.3.8
it works for me, thanks!

**Comment by PrealCent** [comment]
[#](https://github.com/lmstudio-ai/lmstudio-bug-tracker/issues/256#issuecomment-2620673643)


system os: windows 11
lm studio version: 0.3.9
it works for me, thanks!

**Comment by nasirannn** [comment]
> We added a new HF proxying feature in 0.3.9 Build 2 (available in beta [here](https://lmstudio.ai/beta-releases)) that might solve this problem.
> 
> Try this:
> 
> 1. Download + install 0.3.9 b2 from here: https://lmstudio.ai/beta-releases, or switch to the beta channel and update in-app
> 2. Go to Settings (the ⚙️ bottom right) and enable this:
> 
> ![Image](https://github.com/user-attachments/assets/42c18715-be1e-4710-9c1e-06e521b59be5)
> 
> If you try it, please let me know if it worked or not

thanks,it works for me
system os: macOS 15.2

**Comment by mrtnebrle** [comment]
When investigating a bit deeper it seemed like the bundled python did not have permissions for execution.

`[2025-01-30 15:47:42.329] [error] [DelayedInitProvider] Error running delayed init: Unbundle dependencies Error: Process error: spawn /Users/myuser/.cache/lm-studio/extensions/backends/vendor/_amphibian/app-mlx-generate-mac-arm64@11/bin/python EACCES
Command: /Users/myuser/.cache/lm-studio/extensions/backends/vendor/_amphibian/app-mlx-generate-mac-arm64@11/bin/python -I /Users/myuser/.cache/lm-studio/extensions/backends/vendor/_amphibian/app-mlx-generate-mac-arm64@11/postinstall.py
Error output: 
    at ChildProcess.<anonymous> (/Applications/LM Studio.app/Contents/Resources/app/.webpack/main/index.js:231:25345)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[2025-01-30 15:47:42.363] [error] [BackendDownloadProvider] Failed to refresh backends master list TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _0x38d277.<computed>.getBackendsMasterList (/Applications/LM Studio.app/Contents/Resources/app/.webpack/main/index.js:57:10509)
    at async _0x2c5ee3.<computed>.refreshBackendsMasterList (/Applications/LM Studio.app/Contents/Resources/app/.webpack/main/index.js:231:10985)
[2025-01-30 15:47:42.365] [error] [BackendDownloadProvider] Failed to refresh backends master list TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _0x38d277.<computed>.getBackendsMasterList (/Applications/LM Studio.app/Contents/Resources/app/.webpack/main/index.js:57:10509)
    at async _0x2c5ee3.<computed>.refreshBackendsMasterList (/Applications/LM Studio.app/Contents/Resources/app/.webpack/main/index.js:231:10985)
    at async /Applications/LM Studio.app/Contents/Resources/app/.webpack/main/index.js:231:5785`

After performing `chmod +x /Users/myuser/.cache/lm-studio/extensions/backends/vendor/_amphibian/cpython3.11-mac-arm64@4/bin/python3.11` the search and downloads were working again for me.

**Comment by mrtnebrle** [comment]
When investigating my logs it seemed the bundled python did not have proper executable permissions.

```
[2025-01-30` 15:47:42.329] [error] [DelayedInitProvider] Error running delayed init: Unbundle dependencies Error: Process error: spawn /Users/myuser/.cache/lm-studio/extensions/backends/vendor/_amphibian/app-mlx-generate-mac-arm64@11/bin/python EACCES
Command: /Users/myuser/.cache/lm-studio/extensions/backends/vendor/_amphibian/app-mlx-generate-mac-arm64@11/bin/python -I /Users/myuser/.cache/lm-studio/extensions/backends/vendor/_amphibian/app-mlx-generate-mac-arm64@11/postinstall.py
Error output: 
    at ChildProcess.<anonymous> (/Applications/LM Studio.app/Contents/Resources/app/.webpack/main/index.js:231:25345)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[...]
```

After performing `chmod +x /Users/myuser/.cache/lm-studio/extensions/backends/vendor/_amphibian/cpython3.11-mac-arm64@4/bin/python3.11` the model search was working again, but am unable to perform any actions. This is what I see in the logs with Proxy on or off:

```
[2025-01-30 15:57:46.721] [error] [LMSInternal][Client=LM Studio][Endpoint=quickSearchOne] Error in RPC handler: TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _0xeb9a89 (/Applications/LM Studio.app/Contents/Resources/app/.webpack/main/index.js:1:706944)
    at async _0x3443ae.HuggingFaceHubProvider.search (/Applications/LM Studio.app/Contents/Resources/app/.webpack/main/index.js:231:46170)
    at async _0x4649ec.<computed>.quickSearchOne (/Applications/LM Studio.app/Contents/Resources/app/.webpack/main/index.js:231:63968)
    at async Object.handler (/Applications/LM Studio.app/Contents/Resources/app/.webpack/main/index.js:106:45665)
```

**Comment by yagil** [comment]
@mrtnebrle your issue is different. This should fix it for you: https://github.com/lmstudio-ai/lmstudio-bug-tracker/issues/294#issuecomment-2581576638

**Comment by mrtnebrle** [comment]
> [@mrtnebrle](https://github.com/mrtnebrle) your issue is different. This should fix it for you: [#294 (comment)](https://github.com/lmstudio-ai/lmstudio-bug-tracker/issues/294#issuecomment-2581576638)

Fresh install, no `./cache`, fresh copy to `/Applications` - model search returns results, but any click on a model to download results in the below ...

```
[2025-02-01 19:42:43.418] [error] [LMSInternal][Client=LM Studio][Endpoint=quickSearchOne] Error in RPC handler: TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _0xeb9a89 (/Applications/LM Studio.app/Contents/Resources/app/.webpack/main/index.js:1:706944)
    at async _0x3443ae.HuggingFaceHubProvider.search (/Applications/LM Studio.app/Contents/Resources/app/.webpack/main/index.js:231:46170)
    at async _0x4649ec.<computed>.quickSearchOne (/Applications/LM Studio.app/Contents/Resources/app/.webpack/main/index.js:231:63968)
    at async Object.handler (/Applications/LM Studio.app/Contents/Resources/app/.webpack/main/index.js:106:45665)
[2025-02-01 19:42:43.421] [error] [LMSInternal][Client=LM Studio][Endpoint=quickSearchOne] Error in RPC handler: TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _0xeb9a89 (/Applications/LM Studio.app/Contents/Resources/app/.webpack/main/index.js:1:706944)
    at async _0x3443ae.HuggingFaceHubProvider.search (/Applications/LM Studio.app/Contents/Resources/app/.webpack/main/index.js:231:46170)
    at async _0x4649ec.<computed>.quickSearchOne (/Applications/LM Studio.app/Contents/Resources/app/.webpack/main/index.js:231:63968)
    at async Object.handler (/Applications/LM Studio.app/Contents/Resources/app/.webpack/main/index.js:106:45665)
[2025-02-01 19:42:57.049] [error] [LMSInternal][Client=LM Studio][Endpoint=quickSearchOne] Error in RPC handler: TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _0xeb9a89 (/Applications/LM Studio.app/Contents/Resources/app/.webpack/main/index.js:1:706944)
    at async _0x3443ae.HuggingFaceHubProvider.search (/Applications/LM Studio.app/Contents/Resources/app/.webpack/main/index.js:231:46170)
    at async _0x4649ec.<computed>.quickSearchOne (/Applications/LM Studio.app/Contents/Resources/app/.webpack/main/index.js:231:63968)
    at async Object.handler (/Applications/LM Studio.app/Contents/Resources/app/.webpack/main/index.js:106:45665)
```

**Comment by jalr4ever** [comment]
> We added a new HF proxying feature in 0.3.9 Build 2 (available in beta [here](https://lmstudio.ai/beta-releases)) that might solve this problem.
> 
> Try this:
> 
> 1. Download + install 0.3.9 b2 from here: https://lmstudio.ai/beta-releases, or switch to the beta channel and update in-app
> 2. Go to Settings (the ⚙️ bottom right) and enable this:
> 
> ![Image](https://github.com/user-attachments/assets/42c18715-be1e-4710-9c1e-06e521b59be5)
> 
> If you try it, please let me know if it worked or not

Holy crap this button is really quite hidden; why not include it in the chart settings in the top left corner? It works anyhow.

**Comment by manos-msdn** [comment]
> We added a new HF proxying feature in 0.3.9 Build 2 (available in beta [here](https://lmstudio.ai/beta-releases)) that might solve this problem.
...
> If you try it, please let me know if it worked or not

Hugging face search is not working for me the last few days (with or without proxy setting mentioned here), 0.3.10 Build 6, windows 10, tried restarting the app with the proxy setting

Steps to reproduce: just search for "whisper" in the model discovery page

![Image](https://github.com/user-attachments/assets/add02e0e-e7b8-4b50-a40e-3859229a1706)

Interesting, if I search for "granite" for example, or "mistral", or "deepseek" I am not getting the error

**Comment by DaveHoskins** [comment]
I'm getting this with version 3.12 on Windows 10. There is no beta version available.
It just won't find anything.

![Image](https://github.com/user-attachments/assets/fd2fd30d-7981-42fa-8f86-df5b287faee5)

**Comment by joneschunghk** [comment]
> I'm getting this with version 3.12 on Windows 10. There is no beta version available. It just won't find anything.
> 
> ![Image](https://github.com/user-attachments/assets/fd2fd30d-7981-42fa-8f86-df5b287faee5)

same here.
After the new update to 0.3.12, I can search and download the models.
But after downloaded a model, the issue occurred.

Here is the main.log:
```
[2025-03-13 12:00:29.599] [info]  Opening file: C:\Users\Jones\AppData\Roaming\LM Studio\logs\main.log
[2025-03-13 12:01:18.946] [info]  App starting...
[2025-03-13 12:01:18.949] [info]  [AppUpdater] Update channel set to 'stable'
[2025-03-13 12:01:19.129] [info]  Hardware survey for general system resources through 'vulkan' took 176.29ms
[2025-03-13 12:01:19.316] [info]  [AppUpdater] Checking for updates... (current state: idle)
[2025-03-13 12:01:19.316] [info]  AppUpdater state changed to checking-for-updates-periodic
[2025-03-13 12:01:19.317] [info]  [AppUpdater] Fetching version info from https://versions-prod.lmstudio.ai/update/win32/x86/0.3.12
[2025-03-13 12:01:19.347] [error] Error fetching updates: fetch failed
[2025-03-13 12:01:19.348] [info]  AppUpdater state changed to failed-to-check-for-updates
[2025-03-13 12:01:19.348] [info]  AppUpdater state changed to idle
[2025-03-13 12:01:19.442] [error] Failed to fetch model catalog feed TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _0x444a09.<computed>.getModelCatalog (C:\Users\Jones\AppData\Local\Programs\LM Studio\resources\app\.webpack\main\index.js:94:10719)
    at async _0x39e164.<computed>.refreshFeed (C:\Users\Jones\AppData\Local\Programs\LM Studio\resources\app\.webpack\main\index.js:269:48398)
[2025-03-13 12:01:20.352] [error] [BackendDownloadProvider] Failed to refresh backends master list TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _0x444a09.<computed>.getBackendsMasterList (C:\Users\Jones\AppData\Local\Programs\LM Studio\resources\app\.webpack\main\index.js:94:10439)
    at async _0x1aae33.BackendDownloadProvider.refreshBackendsMasterList (C:\Users\Jones\AppData\Local\Programs\LM Studio\resources\app\.webpack\main\index.js:260:11586)
[2025-03-13 12:01:20.401] [error] [BackendDownloadProvider] Failed to refresh backends master list TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _0x444a09.<computed>.getBackendsMasterList (C:\Users\Jones\AppData\Local\Programs\LM Studio\resources\app\.webpack\main\index.js:94:10439)
    at async _0x1aae33.BackendDownloadProvider.refreshBackendsMasterList (C:\Users\Jones\AppData\Local\Programs\LM Studio\resources\app\.webpack\main\index.js:260:11586)
    at async C:\Users\Jones\AppData\Local\Programs\LM Studio\resources\app\.webpack\main\index.js:260:6237
[2025-03-13 12:01:25.244] [error] [LMSInternal][Client=LM Studio][Endpoint=quickSearchOne] Error in RPC handler: TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _0x88c3f8 (C:\Users\Jones\AppData\Local\Programs\LM Studio\resources\app\.webpack\main\index.js:1:893410)
    at async _0xfef8e.HuggingFaceHubProvider.search (C:\Users\Jones\AppData\Local\Programs\LM Studio\resources\app\.webpack\main\index.js:269:32802)
    at async _0x39e164.<computed>.quickSearchOne (C:\Users\Jones\AppData\Local\Programs\LM Studio\resources\app\.webpack\main\index.js:269:50676)
    at async Object.handler (C:\Users\Jones\AppData\Local\Programs\LM Studio\resources\app\.webpack\main\index.js:149:51292)
[2025-03-13 12:01:34.142] [info]  Opening file: C:\Users\Jones\AppData\Roaming\LM Studio\logs\main.log
[2025-03-13 12:01:34.357] [info]  [AppUpdater] Checking for updates... (current state: idle)
[2025-03-13 12:01:34.358] [info]  AppUpdater state changed to checking-for-updates-periodic
[2025-03-13 12:01:34.358] [info]  [AppUpdater] Fetching version info from https://versions-prod.lmstudio.ai/update/win32/x86/0.3.12
[2025-03-13 12:01:34.375] [error] Error fetching updates: fetch failed
[2025-03-13 12:01:34.375] [info]  AppUpdater state changed to failed-to-check-for-updates
[2025-03-13 12:01:34.376] [info]  AppUpdater state changed to idle
```

**Comment by joneschunghk** [comment]
I solved this issue by reinstalling the internet security software

**Comment by tom-papatheodore** [comment]
Hi All. I'm observing this same issue on a fresh install of LM Studio - 0.3.17 on Windows 11 - even with the proxy enabled. Any thoughts on how I can resolve this?

<img width="1907" height="1115" alt="Image" src="https://github.com/user-attachments/assets/1b7db82b-d568-49af-9016-019a79c8f602" />

<img width="1902" height="1111" alt="Image" src="https://github.com/user-attachments/assets/a3debf9c-4669-4209-9c78-3c2d20e887e0" />

**Comment by katfionn** [comment]
I'm just download the least version from official site, yet, it keep happening.
On/Off the switch, won't change anything

<img width="2308" height="1350" alt="Image" src="https://github.com/user-attachments/assets/a19962f7-fc3c-4fda-b381-bf36d9fbae11" />

This model do exist on huggingface, but ican't find it in LM studio

<img width="2880" height="1604" alt="Image" src="https://github.com/user-attachments/assets/d7408caf-6fb9-4a5e-a2be-537451383fbe" />

**Comment by ahf010** [comment]
I have the same problem today is 19 may 2026, my version is updated, 0.4.13, there is no beta version available, I activate and deactivate the proxy tick in settings/General, neither worked, I used VPN and different DNS but it keep saying : There was an error fetching results from Hugging Face, please try again later. any thoughts?

**Comment by NoanWasTaken** [comment]
I have the same issue, here are my logs : 

```
download source {
  type: 'huggingface',
  user: 'lmstudio-community',
  repo: 'gemma-4-E4B-it-GGUF'
} Error: Api error with status 403. URL: https://search.lmstudio.ai/v1/hf-proxy/api/models/lmstudio-community/gemma-4-E4B-it-GGUF/tree/main?recursive=true&expand=false
    at _0x7ed578 (/Applications/LM Studio.app/Contents/Resources/app/.webpack/main/index.js:1:144162)
    at _0x442e76 (/Applications/LM Studio.app/Contents/Resources/app/.webpack/main/index.js:1:180172)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async _0x1fbb00.listFiles (/Applications/LM Studio.app/Contents/Resources/app/.webpack/main/index.js:1364:49569)
    at async _0x528ae7.getModelDownloadOptionsWithConfigJson (/Applications/LM Studio.app/Contents/Resources/app/.webpack/main/index.js:1367:15317)
    at async _0x528ae7.getLocalPlatformSupportedModelDownloadOptions (/Applications/LM Studio.app/Contents/Resources/app/.webpack/main/index.js:1367:16173)
    at async _0x3bdfeb.getModelDownloadOptionsFromDownloadSource (/Applications/LM Studio.app/Contents/Resources/app/.webpack/main/index.js:792:10057)
    at async /Applications/LM Studio.app/Contents/Resources/app/.webpack/main/index.js:796:1543
```

**Comment by donkeyx** [comment]
I get a similar issue with or without the proxy enabled. Is there a debug mode or something with more detail logs? 

```
[2026-04-01 08:21:35.950] [error] Failed to fetch staff picks Error: Network connection failed
    at _0x2e7fb8.<computed>.fetchWithRetry (C:\Users\AAA\AppData\Local\Programs\LM Studio\resources\app\.webpack\main\index.js:804:10558)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async _0x2e7fb8.<computed>.handleFetchUnauthenticatedWithoutParsing (C:\Users\AAA\AppData\Local\Programs\LM Studio\resources\app\.webpack\main\index.js:804:13541)
    at async _0x2e7fb8.<computed>.handleFetchUnauthenticated (C:\Users\AAA\AppData\Local\Programs\LM Studio\resources\app\.webpack\main\index.js:804:13698)
    at async _0xd54d09.getStaffPicks (C:\Users\AAA\AppData\Local\Programs\LM Studio\resources\app\.webpack\main\index.js:294:17186)
    at async _0x12dae4.refreshFeed (C:\Users\AAA\AppData\Local\Programs\LM Studio\resources\app\.webpack\main\index.js:1376:8434)
    at async Object.handler (C:\Users\AAA\AppData\Local\Programs\LM Studio\resources\app\.webpack\main\index.js:608:114881)

```
