### ISSUE TITLE
What is error 133?

### ISSUE THREAD

**Issue by yhojann-cl** [lmstudio-ai/lmstudio-bug-tracker#274]
I try load the Dolphin 2.5 Mixtral 8x7B model downloaded from the lmstudio, but when try load says:

```
🥲 Failed to load the model

Error loading model.

(Exit code: 133). Please check settings and try loading the model again. 
```

Are special manual parameters needed for each model? Doesn't it work to simply download and use the default settings?

I use Ubuntu 22.04 LTS and `LM_Studio-0.3.5.AppImage` binary with `--no-sandbox` argument for prevent sandboxing for the chronium on the electron app.

The console says:

```
[CachedFileDataProvider] File at /home/yhojann/.cache/lm-studio/.internal/gguf-metadata-cache.json is no longer used. Releasing...
[CachedFileDataProvider] Watching file at /home/yhojann/.cache/lm-studio/conversations/1735684822789.conversation.json
[CachedFileDataProvider] File at /home/yhojann/.cache/lm-studio/.internal/user-concrete-model-default-config/TheBloke/dolphin-2.5-mixtral-8x7b-GGUF/dolphin-2.5-mixtral-8x7b.Q4_0.gguf.json is no longer used. Releasing...
[CachedFileDataProvider] Watching file at /home/yhojann/.cache/lm-studio/.internal/user-concrete-model-default-config/TheBloke/dolphin-2.5-mixtral-8x7b-GGUF/dolphin-2.5-mixtral-8x7b.Q4_0.gguf.json
[CachedFileDataProvider] File at /home/yhojann/.cache/lm-studio/.internal/user-concrete-model-default-config/.json is no longer used. Releasing...
19:42:05.397 › [LMSInternal][Client=LM Studio][Endpoint=loadModel] Error in channel handler: Error: Error loading model.
    at f.d (/tmp/.mount_LM_StuvFPr9N/resources/app/.webpack/main/index.js:8:1148205)
    at f.emit (node:events:513:28)
    at f.onChildExit (/tmp/.mount_LM_StuvFPr9N/resources/app/.webpack/main/index.js:8:1124523)
    at ForkUtilityProcess.<anonymous> (/tmp/.mount_LM_StuvFPr9N/resources/app/.webpack/main/index.js:8:1124129)
    at ForkUtilityProcess.emit (node:events:513:28)
    at ForkUtilityProcess.a.emit (node:electron/js2c/browser_init:2:68545)
[LMSInternal][Client=LM Studio][Endpoint=loadModel] Error in loadModel channel g [Error]: Error loading model.
    at f.d (/tmp/.mount_LM_StuvFPr9N/resources/app/.webpack/main/index.js:8:1148205)
    at f.emit (node:events:513:28)
    at f.onChildExit (/tmp/.mount_LM_StuvFPr9N/resources/app/.webpack/main/index.js:8:1124523)
    at ForkUtilityProcess.<anonymous> (/tmp/.mount_LM_StuvFPr9N/resources/app/.webpack/main/index.js:8:1124129)
    at ForkUtilityProcess.emit (node:events:513:28)
    at ForkUtilityProcess.a.emit (node:electron/js2c/browser_init:2:68545) {
  cause: '(Exit code: 133). Please check settings and try loading the model again. ',
  suggestion: '',
  errorData: undefined,
  data: undefined,
  displayData: undefined,
  title: 'Error loading model.'
}
```

**Comment by YorkieDev** [comment]
@yhojann-cl what are the system specs of your machine? 

Dolphin 2.5 Mixtral 8x7B is a beefy Q4_K_M requires 26gb of (vram) ram to run. You might be seeing that error message if you don't have enough vram to load it fully. You can try adjusting the GPU layers that are being offloaded (cog next to model at top of chat UI) so that more of it goes towards your CPU ram, or you can switch runtime(CTRL + SHIFT + R to access LM Runtimes) to CPU llama.cpp to run it entirely in CPU ram.

**Comment by yhojann-cl** [comment]
Desktop, Amd Ryzen 7800X3D, 128GB of ram, 4TB of ssd.M2, 2TB free, AMD Radeon RX 6800 XT (16GB of GDDR6). I use default settings for all.

```bash
yhojann@pc:~$ free
               total       usado       libre  compartido   búf/caché  disponible
Mem:       131823252     9419060   104036368      585764    20200964   122404192
Inter:       8388604           0     8388604

yhojann@pc:~$ swapon -s
Filename				Type		Size		Used	Priority
/swap.img                               file		8388604		0	-2

yhojann@pc:~$ ulimit -a
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) 0
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 514633
max locked memory           (kbytes, -l) 16477904
max memory size             (kbytes, -m) unlimited
open files                          (-n) 1024
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) 8192
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) 514633
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited
```

**Comment by YorkieDev** [comment]
@yhojann-cl Mixtral is too large to run on your GPU entirely which is why you get that error. You need to reduce the number of GPU layers that are offloaded, or go to LM Runtimes(CTRL + SHIFT + R) and switch to CPU llama.cpp. For best performance with models it is recommended to go for ones that say "Full GPU Offload Possible" in the model explorer.

**Comment by yhojann-cl** [comment]
Thank you very much for the clarification. Maybe it would be good if when an error occurs due to lack of hardware capacity it was explicitly indicated through a message that better explains the problem, or perhaps some information box with the minimum hardware requirements for each model so I could know in advance if I could run them.

**Comment by YorkieDev** [comment]
@yhojann-cl for future reference, file size of the model = amount of vram required to run it quickly, you can use CPU ram to run models, but it won't be as fast as running it entirely in your GPU.
